### PR TITLE
vec_pushm to push all the elements from an array

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rxi** [comment]
Firstly, nice job on keeping to the project's style, all your additions fit in perfectly stylistically.

Unfortunately, though the feature itself seems like a good idea, I've a few issues with the implementation. The function itself seems to lose the type-safety -- I appreciate there's no _perfect_ way of implementing the push-an-array-of-elements feature. What I would prefer in such a feature is something similar to what I did with the `vec_extend()` function where I opted for type safety but a lack of error return code -- the rationale is that you can still check for error by checking the vector's resulting length, this seems like a better trade off to keep the entire implementation type safe. I'd probably also have named the function `vec_pusharr()` rather than `vec_pushm()`. If you don't feel like making another pull request with these changes I'll probably add the feature myself at some point.

Additionally it looks like there's a bug on [line 60 of vec.c](https://github.com/joshuagiles/vec/commit/e57e7ed29beca775d4521e67cd62d48b03b0c695#diff-e0244fe17352f875b82711565a4cd610R60), where a vector which already has a large enough capacity that it didn't need to be increased would set the resultant length to this capacity, causing the length to be larger than intended.

Thanks

**Comment by ghost** [comment]
I fixed the capacity bug, and changed the name to pusharr.

I also made the pusharr function type-safe by putting the pusharr_ call inside a ternary conditional, where the 'true' path is the only one ever taken, but the 'false' path will still cause a compiler warning for comparing mismatched pointer types. The idea came from glib where they do the same thing to maintain type-safety, seen here: https://github.com/GNOME/glib/blob/master/glib/gslice.h#L59

So it has type-safety and it also has an error return code :)

**Comment by ghost** [comment]
Currently the behavior is different from `vec_push()` in that it will not silently cast numeral types when mismatched types are used. `vec_pusharr()` will perform the copy without a cast but will also issue a warning at compile-time to let the programmer know that they probably messed up.

This could be changed by making `vec_pusharr()` use a `vec_push()` loop internally, which would allow to push, say, an array of ints to a vector of chars, casting each int in the array as it goes, but no compiler warnings or errors are generated when using mismatched numeral types with `vec_push()`.

**Comment by ghost** [comment]
One final comment here, I did some performance testing, using `vec_pusharr()` instead of `vec_push()` to push 10000 elements to a `vec_int_t` and saw about a 400% speedup. I'm thinking this probably has to do with a `vec_push()` loop requiring a call to `realloc` every time the new capacity is reached, while `vec_pusharr()` will only call `realloc` once at most, eliminating a _large_ amount of allocation overhead.

With this realization I looked at `vec_extend()`, and replaced the entire do...while loop with `vec_pusharr((v), (v2)->data, (v2)->length)`. I tested again by extending an empty vector with a 10000 element vector and also saw a ~400% speedup in execution time. This would also allow `vec_extend()` to return an error code like the rest of the API, if you decide to incorporate that change as well. I'm not committing that change to this PR because it seems a little bit out of scope, but I thought I'd let you know about it anyway.

**Comment by rxi** [comment]
> Currently the behavior is different from vec_push() in that it will not silently cast numeral types when mismatched types are used.
> ...
> but no compiler warnings or errors are generated when using mismatched numeral types with vec_push().

I consider this a feature, and one of the benefits of the implementation. For example, if you have a vector of doubles and want to extend it using a vector of integers, the macro allows the operation and converts rather than warning you of a type error and subsequently not working as expected. Additionally, this functionality is the reason I think the `vec_pusharr()` function should be implemented in a similar fashion.

>  I did some performance testing, using vec_pusharr() instead of vec_push() to push 10000 elements to a vec_int_t and saw about a 400% speedup. I'm thinking this probably has to do with a vec_push() loop requiring a call to realloc every time the new capacity is reached

This is what the `vec_reserve()` function was for -- in cases where you know you'll need a specific capacity and want to avoid unnecessary realloc() calls.  I do understand that even with the `vec_reserve()` call, the operation would still be slower than a straight memcpy(), but I'm under the impression that for the majority of use cases this wouldn't be an issue, that being said I haven't yet benchmarked such a scenario.

I believe with both `vec_pusharr()` and `vec_extend()` it could be made so the capacity is resized to the next-highest-power-of-two in the macro first, then the length modified, then the items copied in a for-loop which, instead of using push, would just access the `.data` members directly -- this for-loop would, I assume, be optimised by the compiler to act as efficiently as the memcpy when pushing the same type, but would also give the benefit I described before of pushing values of a different type to the vector.

This still means we don't have the returned error value, but again, checking the resultant length is correct would be as good as checking the error code.

**Comment by rxi** [comment]
I've added the `vec_pusharr()` function as I described above. I've also changed `vec_extend()` to use `vec_pusharr()` so it should benefit from better performance as it will now only realloc() a maximum of one time per-call.

**Pull request closed without merging**
